site_name: OCX test with MIT OCW Physics III -- Vibrations and Waves
nav:
  - Course Home : index.md
  - Syllabus : syllabus.md
  - Instructor Insights : instructorInsights.md
  - 'Part I: Mechanical Vibrations and Waves' :
    - 'Part I index' : ptI.md
    - 'Lecture 1: Periodic Oscillations, Harmonic Oscillations' : l1.md
  - 'Part II: Electromagnetic Waves' :
    - 'Part II index' : ptII.md
  - 'Part III: Optics' :
    - 'Part III index' : ptIII.md
  - Final Exam : finalExam.md
theme:
  name: 'material'
  palette:
    primary: 'Brown'
    accent: 'Red'
markdown_extensions:
  - admonition
  - ocxsect
  - ocxmd:
      context: '"@context": ["http://schema.org",{"oer":"http://oerschema.org/"},{"ocx":"https://k12ocx.github.io/k12ocx-specs/"}]'
